Qilululi ip branch
SonicCloudOrg/sonic-agent pull request #287
Opened 2022-12-18 08:17 UTC by jimmyshealisa

**在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：**

- [ ] 标题为fix、feat或doc开头
- [ ] 我已检查没有与此请求重复的拉取请求。
- [ ] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。

**填写PR内容：**
可以自动获取agent的ip地址，并添加不同agent部署的系统下的命令号执行工具类

2022-12-18 08:18 UTC, ZhouYixun commented on src/main/java/org/cloud/sonic/agent/tools/CommandTool.java
> +public class CommandTool {
这个类重复了，已经有command的tool，你可以查看一下

2022-12-18 08:21 UTC, ZhouYixun requested changes
感觉暂时来说实用性不是特别高，ip变更之后还是要重启。

另外是win linux这种多网卡的，这个获取结果不是很准确

2022-12-18 08:32 UTC, jimmyshealisa commented
> 

主要是希望能减少配置文件的更改，比如ip变更的话都要重启，但是可以减少更新ip的步骤。
对于多网卡的情况我理解一般是直接获取第一个网卡的地址？我觉得可以在配置文件加一个是否自动获取ip，并说明不一定获取准确

2022-12-18 09:18 UTC, ZhouYixun commented
> > 
> 
> 主要是希望能减少配置文件的更改，比如ip变更的话都要重启，但是可以减少更新ip的步骤。 对于多网卡的情况我理解一般是直接获取第一个网卡的地址？我觉得可以在配置文件加一个是否自动获取ip，并说明不一定获取准确

我个人偏向这里手动填好一点，多网卡在企业里非常多见。不是减少配置与否的关系吧，这个填错了或者自动识别错了，估计社区又一堆连不上的问题。

不过倒是有个新思路。这一块本来就是本机0.0.0.0启动的，agent的ip其实也可以暴露给前端去更新，不在本地填。前端要是更改了agent的ip，就下发给agent更改逻辑里ip就可以了。

2022-12-18 09:46 UTC, jimmyshealisa commented
> > > 
> > 
> > 
> > 主要是希望能减少配置文件的更改，比如ip变更的话都要重启，但是可以减少更新ip的步骤。 对于多网卡的情况我理解一般是直接获取第一个网卡的地址？我觉得可以在配置文件加一个是否自动获取ip，并说明不一定获取准确
> 
> 我个人偏向这里手动填好一点，多网卡在企业里非常多见。不是减少配置与否的关系吧，这个填错了或者自动识别错了，估计社区又一堆连不上的问题。
> 
> 不过倒是有个新思路。这一块本来就是本机0.0.0.0启动的，agent的ip其实也可以暴露给前端去更新，不在本地填。前端要是更改了agent的ip，就下发给agent更改逻辑里ip就可以了。

通过后端服务获取到agent上传的心跳信息来源的ip地址去更新前端agent的ip地址吗，那这一块代码可以去掉了

2022-12-18 09:58 UTC, ZhouYixun commented
> > > > 
> > > 
> > > 
> > > 主要是希望能减少配置文件的更改，比如ip变更的话都要重启，但是可以减少更新ip的步骤。 对于多网卡的情况我理解一般是直接获取第一个网卡的地址？我觉得可以在配置文件加一个是否自动获取ip，并说明不一定获取准确
> > 
> > 
> > 我个人偏向这里手动填好一点，多网卡在企业里非常多见。不是减少配置与否的关系吧，这个填错了或者自动识别错了，估计社区又一堆连不上的问题。
> > 不过倒是有个新思路。这一块本来就是本机0.0.0.0启动的，agent的ip其实也可以暴露给前端去更新，不在本地填。前端要是更改了agent的ip，就下发给agent更改逻辑里ip就可以了。
> 
> 通过后端服务获取到agent上传的心跳信息来源的ip地址去更新前端agent的ip地址吗，那这一块代码可以去掉了

方式有很多，只是Agent自动检测这种我不太建议。

2023-01-01 14:25 UTC, ZhouYixun commented
非常感谢您的贡献，这个pr我先关闭，后续需要讨论时可以重开。或者有更好的想法欢迎继续贡献哦

2023-01-01 14:25 UTC, closed without merging