feat:修改longPress 位置为元素中心;增加swipeByDefinedDirection方法,以屏幕中心为起始 位置,根据自定义像素距离,支持上滑/下滑/左滑/右滑
SonicCloudOrg/sonic-agent pull request #315
Opened 2023-03-05 14:40 UTC by upengfei

> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [ ] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [ ] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [ ] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### Description
1、长按元素的方法我发现有时候并不生效，比如在长按桌面的某个程序希望它弹出一些菜单选择项时。将其长按的位置移动到元素中心位置，可解决该问题。
2、swipeByDefinedDirection 方法有两个参数：slideDirection和distance。slideDirection表示方向，支持上下左右，distance为滑动的距离(像素)。

2023-03-05 16:49 UTC, ZhouYixun requested changes
建议将【手机】改为【设备】

2023-03-05 16:51 UTC, ZhouYixun commented on src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
> +                try {
> handleContext.setDetail("拖动坐标(" + centerX + "," + centerY + ")到(" + targetX + "," + centerY + ")");

这个可以放到外面

2023-03-05 16:52 UTC, ZhouYixun commented
不错的改动，不知道方便补上iOS的中心滑动吗

2023-03-06 01:25 UTC, upengfei commented on src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
> +                try {
ok，我修改下。ios的我研究下~~

2023-03-06 03:04 UTC, ZhouYixun commented on src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
> +                    log.sendStepLog(StepType.INFO,"提示:","滑动距离超出手机底部，默认取底部边界值"+"<"+targetY+">");
提示可以不要，直接空字符串 log.sendStepLog(StepType.INFO,"","滑动距离超出手机底部，默认取底部边界值"+"<"+targetY+">...");

2023-03-06 09:52 UTC, ZhouYixun commented on src/main/java/org/cloud/sonic/agent/tests/handlers/AndroidStepHandler.java
> +
这个应该改成 

>  log.sendStepLog(StepType.INFO,"","设备分辨率为：" + width + "x" + height + " 像素");

2023-03-09 05:13 UTC, ZhouYixun requested changes
swipe的exception应该用setE(e)抛出，print堆栈没有作用

2023-03-09 05:58 UTC, ZhouYixun approved these changes
允许合入

2023-03-09 05:59 UTC, merged